// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kienvan102/monorepo-microservices-template/core/jsonfile"
	"github.com/kienvan102/monorepo-microservices-template/core/logger"
	"github.com/kienvan102/monorepo-microservices-template/services/mongoanalyzer/business"
	"github.com/kienvan102/monorepo-microservices-template/services/mongoanalyzer/jsrunner"
	"github.com/kienvan102/monorepo-microservices-template/services/mongoanalyzer/repository/mongodb"
	"github.com/kienvan102/monorepo-microservices-template/services/mongoanalyzer/settings"
)

// Injectors from wire.go:

// Initialize builds the mongoanalyzer service for this
// deployment: each business port is bound to the adapter implementing it.
// Regenerate wire_gen.go with `go tool wire` in this directory.
func Initialize(cfg settings.Config, log logger.Logger, catalog *jsrunner.Catalog) *business.Analyzer {
	connector := mongodb.NewConnector()
	runner := jsrunner.NewRunner(catalog)
	writer := jsonfile.NewFileWriter()
	analyzer := business.NewAnalyzer(cfg, log, catalog, connector, runner, writer)
	return analyzer
}
